version : '2'

services:
  prova-votacao-app:
    build:
      context: .
      dockerfile: docker-app.dockerfile
    ports:
      - "8383:8383"
#    networks:
#      - net-backendr
    depends_on:
      - prova-votacao-db

  prova-votacao-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: prova
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
#    networks:
#      - net-backend

  prova-votacao-rabbitmq:
    image: rabbitmq:3.6.6-management
    restart: always
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
      - "5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq:rw
      - ./conf/definitions.json:/opt/definitions.json:ro
      - ./conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

#networks:
#  net-backend:

volumes:
  db_data:
  rabbitmq: