spring:
  application:
    name: prova-votacao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prova-votacao-db:3306/prova
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  rabbitmq:
    host: prova-votacao-rabbitmq
    port: 5672
    username: guest
    password: guest

notificacao:
  exchange: exchange.resultado
  routing-Key: "#"

server:
  port: 8383


