CREATE TABLE SESSAO (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    CODIGO_PAUTA INTEGER,
    DATA_ABERTURA DATETIME NOT NULL,
    DATA_ENCERRAMENTO DATETIME NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL,
    CONSTRAINT PK_SESSAO PRIMARY KEY (CODIGO),        
    CONSTRAINT FK_SESSAO_PAUTA
	FOREIGN KEY (CODIGO_PAUTA)
	REFERENCES PAUTA(CODIGO)
);