CREATE TABLE VOTACAO (
	CODIGO INTEGER NOT NULL AUTO_INCREMENT,
    CODIGO_SESSAO INTEGER NOT NULL,
    CODIGO_ASSOCIADO INTEGER NOT NULL,    
    OPCAO VARCHAR(3) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL,
    CONSTRAINT PK_VOTACAO PRIMARY KEY (CODIGO),
    
    CONSTRAINT FK_VOTACAO_SESSAO
	FOREIGN KEY (CODIGO_SESSAO)
	REFERENCES SESSAO(CODIGO),
    
    CONSTRAINT OPCAO_CK CHECK (OPCAO IN ('Sim','Não'))
);